// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWJP6z3pxB_fXq1HWlhL6j-6RLMzCC978',
    appId: '1:192309262666:web:80d368212488e0c30969b3',
    messagingSenderId: '192309262666',
    projectId: 'ctse-33fa4',
    authDomain: 'ctse-33fa4.firebaseapp.com',
    storageBucket: 'ctse-33fa4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAosRSepuNIzDbhLykLsFcGqfWoGI0YTq0',
    appId: '1:192309262666:android:69b0333ecf1268c80969b3',
    messagingSenderId: '192309262666',
    projectId: 'ctse-33fa4',
    storageBucket: 'ctse-33fa4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAwkiKMRNwx7HSSHp9o_a6Ddj7lt6qOqc',
    appId: '1:192309262666:ios:ca9457390daf670c0969b3',
    messagingSenderId: '192309262666',
    projectId: 'ctse-33fa4',
    storageBucket: 'ctse-33fa4.appspot.com',
    iosClientId: '192309262666-ros71aodtsqvd87v9dtg9v0mtvrtubpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAwkiKMRNwx7HSSHp9o_a6Ddj7lt6qOqc',
    appId: '1:192309262666:ios:ca9457390daf670c0969b3',
    messagingSenderId: '192309262666',
    projectId: 'ctse-33fa4',
    storageBucket: 'ctse-33fa4.appspot.com',
    iosClientId: '192309262666-ros71aodtsqvd87v9dtg9v0mtvrtubpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctseProject',
  );
}
