// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfnZ1601yUrxq7z6XX_RvPs4SzndtuwTc',
    appId: '1:417629989867:web:1755a4f1a0dc7fa00b87ae',
    messagingSenderId: '417629989867',
    projectId: 'flutterauth-cae55',
    authDomain: 'flutterauth-cae55.firebaseapp.com',
    storageBucket: 'flutterauth-cae55.appspot.com',
    measurementId: 'G-DZR7LQBP13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBebgen09U3zyLOhxYa_AvTUXjRLDN7K2s',
    appId: '1:417629989867:android:8318a2aca08f7cb50b87ae',
    messagingSenderId: '417629989867',
    projectId: 'flutterauth-cae55',
    storageBucket: 'flutterauth-cae55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaTFqilb4vyUHFk2F3FplUpAQeJAlqt-8',
    appId: '1:417629989867:ios:0711a89332ec89080b87ae',
    messagingSenderId: '417629989867',
    projectId: 'flutterauth-cae55',
    storageBucket: 'flutterauth-cae55.appspot.com',
    iosClientId: '417629989867-kusj6tlku3r6js5t40vj2em9hpt8isbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.it20004668Labinclasstest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaTFqilb4vyUHFk2F3FplUpAQeJAlqt-8',
    appId: '1:417629989867:ios:0711a89332ec89080b87ae',
    messagingSenderId: '417629989867',
    projectId: 'flutterauth-cae55',
    storageBucket: 'flutterauth-cae55.appspot.com',
    iosClientId: '417629989867-kusj6tlku3r6js5t40vj2em9hpt8isbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.it20004668Labinclasstest',
  );
}
